In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("../data/raw/nepali_housing.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 2211
Number of columns: 18

In [4]:
df.head()

,Title,Address,City,Price,Bedroom,Bathroom,Floors,Parking,Face,Year,Views,Area,Road,Road Width,Road Type,Build Area,Posted,Amenities
0,Flat System House On Sale At Budhanikantha : H...,"Budhanikantha, Budhanilkantha, Kathmandu",Kathmandu,90000000,6,3,2.0,10,West,2073.0,17,1-0-0-0 Aana,20 Feet / Blacktopped,20 Feet,Blacktopped,18-0-0-0 Aana,11 hours ago,"['Parking', 'Lawn', 'Garage', 'Frontyard', 'Fe..."
1,21 Aana Beautiful House : House For Sale In Bu...,"Pasikot, Budhanilkantha, Kathmandu",Kathmandu,80000000,5,3,2.0,9,East,2073.0,26,0-21-0-0 Aana,20 Feet / Blacktopped,20 Feet,Blacktopped,0-14-0-0 Aana,12 hours ago,"['Parking', 'Garage', 'Fencing', 'Frontyard', ..."
2,Beautiful To Floor House : House For Sale In D...,"Dhapasi, Dhapasi, Kathmandu",Kathmandu,70000000,5,3,2.0,12,East,2071.0,154,1-1-0-0 Aana,20 Feet / Blacktopped,20 Feet,Blacktopped,10-1-0-0 Aana,2 days ago,"['Parking', 'Lawn', 'Garage', 'Frontyard', 'Fe..."
3,Modern Architecture Bungalow House : House For...,"baluwatar, Baluwatar, Kathmandu",Kathmandu,130000000,6,4,3.0,9,West,2017.0,17,0-10-1-0 Aana,20 Feet / Blacktopped,20 Feet,Blacktopped,0-7-1-0 Aana,1 day ago,"['Parking', 'Lawn', 'Garage', 'Frontyard', 'Fe..."
4,Modern Bungalow House : House For Sale In Golf...,"Golfutar, Golfutar, Kathmandu",Kathmandu,100000000,6,3,2.0,10,East,2070.0,59,0-19-2-0 Aana,20 Feet / Blacktopped,20 Feet,Blacktopped,0-14-2-0 Aana,2 days ago,"['Parking', 'Lawn', 'Garage', 'Balcony', 'Back..."

In [5]:
print("Columns:")
print(df.columns.tolist())

Columns:
['Title', 'Address', 'City', 'Price', 'Bedroom', 'Bathroom', 'Floors', 'Parking', 'Face', 'Year', 'Views', 'Area', 'Road', 'Road Width', 'Road Type', 'Build Area', 'Posted', 'Amenities']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2211 entries, 0 to 2210
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       2211 non-null   object
 1   Address     2211 non-null   object
 2   City        2211 non-null   object
 3   Price       2211 non-null   int64
 4   Bedroom     2211 non-null   int64
 5   Bathroom    2211 non-null   int64
 6   Floors      1039 non-null   float64
 7   Parking     2211 non-null   int64
 8   Face        2211 non-null   object
 9   Year        582 non-null    float64
 10  Views       2211 non-null   object
 11  Area        2211 non-null   object
 12  Road        2211 non-null   object
 13  Road Width  2211 non-null   object
 14  Road Type   1426 non-null   object
 15  Build Area  2211 non-null   object
 16  Posted      2211 non-null   object
 17  Amenities   2211 non-null   object
dtypes: float64(2), int64(4), object(12)
memory usage: 311.1+ KB

In [7]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Title            0
Address          0
City             0
Price            0
Bedroom          0
Bathroom         0
Floors        1172
Parking          0
Face             0
Year          1629
Views            0
Area             0
Road             0
Road Width       0
Road Type      785
Build Area       0
Posted           0
Amenities        0
dtype: int64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [9]:
df.describe(include="all")

,Title,Address,City,Price,Bedroom,Bathroom,Floors,Parking,Face,Year,Views,Area,Road,Road Width,Road Type,Build Area,Posted,Amenities
count,2211,2211,2211,2.211000e+03,2211.000000,2211.000000,1039.000000,2211.000000,2211,582.000000,2211,2211,2211,2211,1426,2211,2211,2211
unique,1502,1588,32,NaN,NaN,NaN,NaN,NaN,8,NaN,784,604,176,100,6,262,20,764
top,"House For Sale In Imadol, Lalitpur","Na, Budhanilkantha, Kathmandu",Kathmandu,NaN,NaN,NaN,NaN,NaN,East,NaN,1.2K,4 Aana,0 Feet,13 Feet,Blacktopped,N/A Sq. Feet,1 year ago,[]
freq,38,38,1483,NaN,NaN,NaN,NaN,NaN,745,NaN,29,163,173,296,749,931,506,1067
mean,NaN,NaN,NaN,4.064428e+11,2.731796,1.871099,2.824206,1.007689,NaN,2057.780069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,7.564269e+12,4.174364,2.635836,1.265411,2.094905,NaN,26.098577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1.500000e+01,0.000000,0.000000,0.000000,0.000000,NaN,1994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.300000e+06,0.000000,0.000000,2.000000,0.000000,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,8.000000e+06,0.000000,0.000000,3.000000,0.000000,NaN,2074.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.650000e+07,5.000000,4.000000,3.000000,1.000000,NaN,2076.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2.160000e+14,95.000000,40.000000,13.000000,31.000000,NaN,2077.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print("PRICE VALUES")
print(df["Price"].head(20).to_string(index=False))

PRICE VALUES
 90000000
 80000000
 70000000
130000000
100000000
100000000
 11000000
 50000000
100000000
 32500000
 32000000
 39900000
 15000000
 52500000
 26500000
 25500000
 33000000
 18500000
 62000000
 10500000

In [11]:
print("AREA VALUES")
print(df["Area"].head(20).to_string(index=False))

AREA VALUES
 1-0-0-0 Aana
0-21-0-0 Aana
 1-1-0-0 Aana
0-10-1-0 Aana
0-19-2-0 Aana
0-12-3-1 Aana
   3-1-1 Aana
 0-8-5-0 Aana
0-12-3-2 Aana
 0-4-0-0 Aana
      14 Aana
 0-4-2-0 Aana
       5 Aana
       8 Aana
       4 Aana
       4 Aana
 0-6-0-0 Aana
       6 Aana
      10 Aana
 0-4-0-0 Aana

In [12]:
print("BUILD AREA VALUES")
print(df["Build Area"].head(20).to_string(index=False))

BUILD AREA VALUES
18-0-0-0 Aana
0-14-0-0 Aana
10-1-0-0 Aana
 0-7-1-0 Aana
0-14-2-0 Aana
 0-8-3-1 Aana
     N/A Aana
 0-6-5-0 Aana
 0-9-3-2 Aana
    2394 Aana
       7 Aana
    2500 Aana
     N/A Aana
     N/A Aana
     N/A Aana
2700 Sq. Feet
     N/A Aana
     N/A Aana
     N/A Aana
     N/A Aana

In [13]:
print("ROAD WIDTH VALUES")
print(df["Road Width"].head(20).to_string(index=False))

ROAD WIDTH VALUES
20 Feet
20 Feet
20 Feet
20 Feet
20 Feet
13 Feet
11 Feet
20 Feet
20 Feet
12 Feet
15 Feet
14 Feet
12 Feet
20 Feet
13 Feet
13 Feet
20 Feet
 13 Feet
  0 Feet
 10 Feet

In [14]:
print("VIEWS VALUES")
print(df["Views"].head(20).to_string(index=False))

VIEWS VALUES
  17
  26
 154
  17
  59
  92
 317
 618
 110
2.6K
 922
 592
 766
 872
1.1K
1.6K
2.8K
 404
 164
 460

In [15]:
print("AREA UNIQUE VALUES")
print(df["Area"].unique()[:30])

print("\nBUILD AREA UNIQUE VALUES")
print(df["Build Area"].unique()[:30])

print("\nROAD WIDTH UNIQUE VALUES")
print(df["Road Width"].unique()[:30])

print("\nPRICE UNIQUE VALUES")
print(df["Price"].unique()[:30])

AREA UNIQUE VALUES
['1-0-0-0 Aana' '0-21-0-0 Aana' '1-1-0-0 Aana' '0-10-1-0 Aana'
 '0-19-2-0 Aana' '0-12-3-1 Aana' '3-1-1 Aana' '0-8-5-0 Aana'
 '0-12-3-2 Aana' '0-4-0-0 Aana' '14 Aana' '0-4-2-0 Aana' '5 Aana' '8 Aana'
 '4 Aana' '0-6-0-0 Aana' '6 Aana' '10 Aana' '0-3-2-0 Aana' '21 Aana'
 '19 Aana' '6.1 Aana' '6.5 Aana' '0-3-0-0 Aana' '3-0-2 Aana' '4 Ropani'
 '4 ana Aana' '7 Aana' '2500 Sq. Feet' '3.1 Aana']

BUILD AREA UNIQUE VALUES
['18-0-0-0 Aana' '0-14-0-0 Aana' '10-1-0-0 Aana' '0-7-1-0 Aana'
 '0-14-2-0 Aana' '0-8-3-1 Aana' 'N/A Aana' '0-6-5-0 Aana' '0-9-3-2 Aana'
 '2394 Aana' '7 Aana' '2500 Aana' '2700 Sq. Feet' '2100 Sq. Feet'
 'N/A Sq. Feet' '2700 Aana' '112 Sq. Meter' '3-0-2 Aana' '4 Aana'
 '2200 Sq. Feet' '2000 Sq. Feet' '3 Aana' '4000 Sq. Feet'
 '0-3-1-2 Sq. Feet' '1736 Dhur' '3500 Aana' '0-4-0-0 Aana' '1900 Sq. Feet'
 '2500 Sq. Feet' '750 Aana']

ROAD WIDTH UNIQUE VALUES
['20 Feet ' '13 Feet ' '11 Feet ' '12 Feet ' '15 Feet ' '14 Feet '
 '13 Feet' '0 Feet' '10 Feet' '10 Feet ' '32 Feet' '16 Feet ' '18 Feet '
 '15 Feet' '26 Feet ' '6 Meter ' '29 Feet' '20 Feet' '6 Meter' '12 Feet'
 '22 Feet' '40 Feet ' '16 Feet' '11 Feet' '30 Feet ' '58 Feet ' '26 Feet'
 '35 Feet ' '18 Feet' '7 Meter ']

PRICE UNIQUE VALUES
[ 90000000  80000000  70000000 130000000 100000000  11000000  50000000
  32500000  32000000  39900000  15000000  52500000  26500000  25500000
  33000000  18500000  62000000  10500000  20500000  22000000 145000000
  55000000  24000000  37000000 102500000  58500000  21000000  17500000
 105000000  27500000]

In [16]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [17]:
print("Statistical Summary")
df.describe()

Statistical Summary

,Price,Bedroom,Bathroom,Floors,Parking,Year
count,2.211000e+03,2211.000000,2211.000000,1039.000000,2211.000000,582.000000
mean,4.064428e+11,2.731796,1.871099,2.824206,1.007689,2057.780069
std,7.564269e+12,4.174364,2.635836,1.265411,2.094905,26.098577
min,1.500000e+01,0.000000,0.000000,0.000000,0.000000,1994.000000
25%,1.300000e+06,0.000000,0.000000,2.000000,0.000000,2020.000000
50%,8.000000e+06,0.000000,0.000000,3.000000,0.000000,2074.000000
75%,2.650000e+07,5.000000,4.000000,3.000000,1.000000,2076.000000
max,2.160000e+14,95.000000,40.000000,13.000000,31.000000,2077.000000

In [18]:
print("Categorical Columns Summary")
df.describe(include="object").T

Categorical Columns Summary

           count unique                                 top  freq
Title       2211   1502  House For Sale In Imadol, Lalitpur    38
Address     2211   1588       Na, Budhanilkantha, Kathmandu    38
City        2211     32                           Kathmandu  1483
Face        2211      8                                East   745
Views       2211    784                                1.2K    29
Area        2211    604                              4 Aana   163
Road        2211    176                              0 Feet   173
Road Width  2211    100                            13 Feet    296
Road Type   1426      6                         Blacktopped   749
Build Area  2211    262                        N/A Sq. Feet   931
Posted      2211     20                          1 year ago   506
Amenities   2211    764                                  []  1067

In [19]:
print("Cities:")
print(df["City"].unique())

print("\nFaces:")
print(df["Face"].unique())

print("\nRoad Types:")
print(df["Road Type"].unique())

Cities:
['Kathmandu' 'Lalitpur' 'Pokhara' 'Bhaktapur' 'Chitwan' 'Butwal' 'Bara'
 'Birtamod' 'Dharan' 'Sunsari' 'Makwanpur' 'Nawalpur' 'Kirtipur'
 'Biratnagar' 'Parsa' 'Itahari' 'Jhapa' 'Mahottari' 'Dhading' 'Bardiya'
 'Morang' 'Dang' 'Kavre' 'Kaski' 'Surkhet' 'Bhairahawa' 'Kapilvastu'
 'Rupandehi' 'Tanahu' 'Illam' 'Nawalparasi' 'Kailali']

Faces:
['West' 'East' 'South East' 'North' 'South West' 'North West' 'South'
 'North East']

Road Types:
[' Blacktopped' ' Gravelled' ' Concrete' ' Paved' nan ' Soil Stabilized'
 ' Alley']